#########################################################################
#      Copyright (C) 2020        Sebastian Francisco Colomar Bauza      #
#      SPDX-License-Identifier:  GPL-2.0-only                           #
#########################################################################
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: phpinfo-cm
data:
  index.php: <?php phpinfo();?>
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: phpinfo
  name: phpinfo-deploy
spec:
  containers:
  - 
    args:
    - -f
    - index.php
    - -S
    - 0.0.0.0:8080
    command:
    - php
    image: docker.io/library/php:latest
    name: phpinfo-container
    volumeMounts:
    - 
      mountPath: /src/index.php
      name: phpinfo-volume
      readOnly: true
      subPath: index.php
    workingDir: /src/
  volumes:
  - 
    configMap:
      defaultMode: 0400
      items: 
      -
        key: index.php
        mode: 0400
        path: index.php
      name: phpinfo-cm
    name: phpinfo-volume
---
apiVersion: v1
kind: Service
metadata:
  name: phpinfo
spec:
  ports:
  - 
    port: 80
    targetPort: 8080
  selector:
    app: phpinfo
  type: ClusterIP
---
